inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - klimt.gemspec
    - vendor/**/*

Metrics/LineLength:
  Max: 132 # good for desktop Github

Metrics/BlockLength:
  Exclude:
    - spec/**/*


Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent
